Event description and location in mail
ephios-dev/ephios pull request #178
Opened 2020-10-16 22:07 UTC by gritfessel

closes #160

2020-10-16 23:19 UTC, jeriox approved these changes

2020-10-17 00:42 UTC, felixrindt reviewed
We could render the description as markdown in the future...

2020-10-17 11:53 UTC, felixrindt requested changes

2020-10-17 11:53 UTC, felixrindt commented on ephios/event_management/mail.py
> +        url=SITE_URL,
can you use urljoin here to join SITE_URL and the event url?

2020-10-17 11:53 UTC, felixrindt commented on ephios/event_management/mail.py
> +        url=SITE_URL,
and than have one less format kwarg

2020-10-18 17:31 UTC, felixrindt approved these changes

2020-10-18 17:33 UTC, merged